Company search page added (nsg basic information)
Virtual-Finland-Development/virtual-finland-demo pull request #10
Opened 2023-03-20 07:29 UTC by LauriGofore

Companies search page, show nsg basic information in preview expander.

Made preview expander component "dumb", does not connect to company context anymore. Can be provided with generic object type for values. Changes accordingly to Preview.

2023-03-20 09:11 UTC, lsipii commented on lib/api/api-client.ts
> +  `${TESTBED_API_BASE_URL}/testbed/productizer/nsg/basic-information?source=fi`,
Näiden `nsg/basic-information` -reittien ei pitäisi tarvita authorisointia elikkäs nämä voi jättää pois tästä patternista.

2023-03-20 09:31 UTC, LauriGofore commented on lib/api/api-client.ts
> +  `${TESTBED_API_BASE_URL}/testbed/productizer/nsg/basic-information?source=fi`,
Alrite, aikaisemmin vielä siitä heitti herjaa, niin siksi oli. Voisi sitten tuossa tapauksessa enabloida tuon company-haun myös ei-autentikoiduille käyttäjille.

2023-03-20 16:49 UTC, lsipii requested changes
Lokaalissa toimii ihan just hyvin 👍
Tuon yhden tyyppivihreän joka tulis hajoamaan pipelinessä vois korjata.

2023-03-20 16:49 UTC, lsipii commented on pages/company/components/preview/preview.tsx
> +  const trackedDoneSteps = Object.keys(doneSteps)
Tähän on samakaltainen operaatio toisaalla ja se ei mene buildista läpi tyypityksen kanssa, kuten tässä kohti menee.

Särkivä kohta: https://github.com/Virtual-Finland-Development/virtual-finland/blob/main/pages/company/components/company-wizard/company-wizard-nav.tsx#L90

2023-03-20 16:49 UTC, lsipii commented on pages/company/components/preview/preview-expander.tsx
> +          {allStepsDone !== undefined && (
Tässä ja vastaavissa ehkä luettavuutta parantaisi jos tsekataan että onko muuttuja boolean, lähinnä koska ollaan ihmeellisessä js-maailmassa: `typeof allStepsDone === 'boolean'`, tai sit jotenkin selventämällä tilamuuttujaa että staattisesti on perisavolainen boolean. Toimii kyllä näinkii ihan juu!

2023-03-20 18:29 UTC, lsipii commented on pages/company/search/index.page.tsx
> +const SOURCE_OPTIONS = [
Tähän voisi lisätä tuon PRH-mock vaihtiksen näillä arvoilla:

```
{
    labelText: 'Virtual Finland',
    name: 'Virtual Finland',
    uniqueItemId: 'virtualfinland',
  },
 ```
 Tai jos oikein kässäsin niin `uniqueItemId` on tässä sama kuin `source` -urlin parametri mitä lähetetään kyselyn mukana. 
 
 Tämä ei rupea toimimaan välttämättä vielä hetkeen kun tarvitsee testbedin päähän konffausta, mutta tuolla source-paramssilla sen pitäisi toimia.

2023-03-20 18:54 UTC, lsipii commented on pages/company/search/index.page.tsx
> +const SOURCE_OPTIONS = [
Tsekattu että testbed-api:n lokaalissa ajossa pitäis nyt käyttää lokaalia prh-mockia, dev-livessä pörräävä dev-liven mockia ja samoin staging-livessä.

2023-03-21 06:41 UTC, LauriGofore commented on pages/company/search/index.page.tsx
> +const SOURCE_OPTIONS = [
Joo, tuo FormSingleSelect input on suomifi-ui-components select inputin päälle tehty, missä ei itse asiassa tarkemalla tarkastuksella tuota name propertya tarvitse noissa valinnoissa (en ollut edes sitä merkinnyt vaadituksi tyypityksissä, heh), mutta esimerkin omaisesti otettu tuolta noiden dokumentaatiosta, eikä edes selitetty miksi name pitäisi erikseen olla, kun ei selvästikään tarvitse. Noiden dokumentaatio on vähän so-so aina välistä. Mutta uniqueItemId vaadittu ja juurikin optionin arvo.

2023-03-21 06:51 UTC, LauriGofore commented on pages/company/search/index.page.tsx
> +const SOURCE_OPTIONS = [
> Tsekattu että testbed-api:n lokaalissa ajossa pitäis nyt käyttää lokaalia prh-mockia, dev-livessä pörräävä dev-liven mockia ja samoin staging-livessä: eli kunhan vain frontti kyselee testbed-api:lta `source`-paramssilla `virtualfinland` niin pitäisi toimia oikein kaikissa ympyröissä.

Ymmärsinkö oikein, että tuo pitäisi toimia jo tuolla uudella paramsilla? 404 heittää itsellä, kun jotain omaa yritystä koitin haeskella.

Tuleeko tuolla paramsilla 404 error koodia? Noiden muiden kohdalla jos ei löydy, heittää 422 -> saisko nämä jotenkin yhtenäistettyä, jos menee eri tavalla tällä hetkellä?

2023-03-21 07:37 UTC, lsipii commented on pages/company/search/index.page.tsx
> +const SOURCE_OPTIONS = [
> Ymmärsinkö oikein, että tuo pitäisi toimia jo tuolla uudella paramsilla? 404 heittää itsellä, kun jotain omaa yritystä koitin haeskella.

Meitsi sai lokaalissa haettua omia testiyrityksiä ihan ok, tarvitsee pullata testbed-api ja prh-mock (joka pitää rebuildata jos ajaa dockerilla).

> Tuleeko tuolla paramsilla 404 error koodia? Noiden muiden kohdalla jos ei löydy, heittää 422 -> saisko nämä jotenkin yhtenäistettyä, jos menee eri tavalla tällä hetkellä?

Minulla tulee myös 404 jos yritystä ei löydy sekä lokaalilla että suomi-norja:lla, en saa nyt 422, mutta sen pitäisi aina tarkoittaa tiedon validaatioerhettä ja taitais tullakin esim. jos tieto ei mätsää testbedin kuvausta.

2023-03-21 07:43 UTC, LauriGofore commented on pages/company/search/index.page.tsx
> +const SOURCE_OPTIONS = [
pullasin kyllä kaiken uusimman, kokeillaas vielä...

2023-03-21 07:47 UTC, lsipii commented on pages/company/search/index.page.tsx
> +const SOURCE_OPTIONS = [
> Minulla tulee myös 404 

testbed-api:lla oli reititysvirhe että se haki lokaalista jos yritti hakea suomi-ruotsista -> tuli 404 vaikka yritys olis ollut olemassa: fixd!

2023-03-21 07:48 UTC, lsipii approved these changes

2023-03-21 07:53 UTC, LauriGofore commented on pages/company/search/index.page.tsx
> +const SOURCE_OPTIONS = [
> > Minulla tulee myös 404
> 
> testbed-api:lla oli reititysvirhe että se haki lokaalista jos yritti hakea suomi-ruotsista -> tuli 404 vaikka yritys olis ollut olemassa: fixd!

Hetken aikaa pelitti tuolla virtualfinland paramsilla, mutta uusimman pulleroisen jälkeen ei

2023-03-21 07:56 UTC, LauriGofore commented on pages/company/search/index.page.tsx
> +const SOURCE_OPTIONS = [
http://localhost:3003/testbed/productizer/nsg/basic-information?source=se
Status Code: 422 Unprocessable Entity
msg: "No results found with given nationalIdentifier"

<--- eli näillä oikeilla sourceilla jos ei löydy, tulee 422 vs. virtualfinland heittää 404

2023-03-21 08:16 UTC, lsipii commented on pages/company/search/index.page.tsx
> +const SOURCE_OPTIONS = [
Joo näinpä on, ne finose:n toteutuksissa lähettävät `422 Unprocessable Entity`, joka korvaani kuulostaa väärälle signaalille, mutta johon ei voida vaikuttaa muutoin kuin testbed-api:n päässä tekemällä muunnos.

2023-03-21 10:43 UTC, merged